spring:
  activemq:
    broker-url: tcp://activemq:61616
  datasource:
    url: jdbc:postgresql://postgres:5432/product
    username: admin
    password: secret
inventory:
  url: https://inventory:9443/inventory/
