spring:
  activemq:
    broker-url: tcp://localhost:61616
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: admin
    password: secret
inventory:
  url: http://localhost:9080/inventory/
